"""phone number edit

Revision ID: 328c875fc756
Revises: ffb48bf1ee80
Create Date: 2022-04-08 19:05:51.155618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328c875fc756'
down_revision = 'ffb48bf1ee80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('users_phone_number_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_phone_number_key', 'users', ['phone_number'])
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
